name: Update README

on:
  workflow_dispatch:

jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.GIT_USER }}

      - name: Generate
        uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://blog.griefed.de/feed'
          file: 'README.md'
          format: '<div align="center">${monthshort} ${02day} - <a href="${url}">${title}</a></div>'

      - name: Add GitHub Sponsors to Readme
        uses: JamesIves/github-sponsors-readme-action@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: |
          apt-get update && apt-get install git -y && \
          git config user.name ${{ secrets.GIT_USER }} && \
          git config user.email ${{ secrets.GIT_MAIL }} && \
          git checkout -b master && \
          pwd && ls -ahl && \
          git add . && \
          wait && \
          git status && \
          git commit -m 'Update fancy schmancy blog posts, sponsors and contribution graph' && \
          git push "https://${{ secrets.GIT_USER }}:${{ secrets.GITLAB_TOKEN }}@${{ secrets.CI_SERVER_HOST }}/${{ secrets.GIT_USER }}/${{ secrets.GIT_USER }}.git" --all
